curl -X 'POST' \
  'http://thefurniturebros.com/auth/register' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "name": "samplz",
  "email": "tesz12@gmail.com",
  "password": "123456",
  "admin": false
}'